# Generated by Django 4.2.6 on 2023-10-30 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('yosh', models.SmallIntegerField()),
                ('kurs', models.SmallIntegerField()),
                ('student_raqam', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Malumot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=255)),
                ('sana', models.DateField()),
                ('b_malumot', models.CharField(max_length=255)),
                ('bajatilgan', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.student')),
            ],
        ),
    ]
