# Generated by Django 4.2.6 on 2023-10-30 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='malumot',
            old_name='b_malumot',
            new_name='malumot',
        ),
    ]
